# -*- coding: utf-8 -*-
"""test_pca.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LLtwM2FwHDCc3kinElllJsAxFH6FE9bC
"""

import unittest
import os
import sklearn
import numpy as np
from sklearn.preprocessing import StandardScaler
import SimpleITK as sitk
import glob
from sklearn.decomposition import PCA

PATH = os.path.abspath('')
FILE = '/tests/smwc1CTRL-1.nii'
FILE = PATH+FILE

img = sitk.ReadImage(FILE, imageIO = "NiftiImageIO")
img_a = sitk.GetArrayFromImage(img[:, 40, :])

class PCATest(unittest.TestCase):

    def setUp(self):
        self.X = img_a
        self.n_comp = 3

    def test_fit(self):

        self.X = StandardScaler().fit_transform(self.X)

        s_pca = sklearn.decomposition.PCA()
        s_pca.fit(self.X)
        s_cumulative_variance_explained=np.cumsum(s_pca.explained_variance_)

        covariance_matrix = np.cov(self.X.T)
        eigen_values, eigen_vectors = np.linalg.eig(covariance_matrix)

        explained_variances_ratio = []
        for i in range(len(eigen_values)):
          explained_variances_ratio.append((eigen_values[i] / np.sum(eigen_values)))


        self.assertEqual(np.array(explained_variances_ratio).shape, s_pca.explained_variance_ratio_.shape)
        np.testing.assert_array_almost_equal(np.array(explained_variances_ratio),
                                             s_pca.explained_variance_ratio_, decimal=2)

if __name__=='__main__':
    unittest.main()
