# -*- coding: utf-8 -*-
"""CEV.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F3zxDwhSS79kzDAXoRjYyRW6HCT4Z0XL
"""

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import numpy as np

def CumExplainedVariance(data):
    '''
    CumExplainedVariance return a 1D array that contain the cumulative explained variance of a dataset.

    Parameters
    ----------
    data : ndarray
        Array obtained from all images.

    Returns
    -------
    Return a one-dimentional array with shape(n_samples)

    '''
    standardized_data = StandardScaler().fit_transform(data)
    pca = PCA()
    principalComponents = pca.fit_transform(standardized_data)
    ex_var_ratio = pca.explained_variance_ratio_
    ex_var = pca.explained_variance_
    cumulative_variance_explained = np.cumsum(ex_var_ratio)
    return cum_var_exp

cum_var_exp = CumExplainedVariance(dataset)
