# -*- coding: utf-8 -*-
"""CEV_cv.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xoFO1A9zbBR67uMEZkCTq66iC8Z4IMJr
"""

from matplotlib import pyplot as plt
import seaborn as sns

def cev_cv(x, y):
    '''
    cev_cv plots the cumulative explained variance with possible number of components to choose a right range of PCs.

    Parameters
    ----------
    x : ndarray or list
        Number of possible PCs (n_samples)
    y : ndarray
        Cumulative explained variance (n_samples)

    Returns
    -------
    lineplot : Plot
    '''

    sns.lineplot(x, y, label='cumulative explained variance')
    plt.xlabel("Number of components")
    plt.ylabel("Cumulative explained variance (%)")
    plt.axhline(y = 0.95, color='k', linestyle='--', label = '95% Explained Variance')
    plt.axhline(y = 0.90, color='c', linestyle='--', label = '90% Explained Variance')
    plt.axhline(y = 0.85, color='r', linestyle='--', label = '85% Explained Variance')
    plt.axhline(y = 0.80, color='y', linestyle='--', label = '80% Explained Variance')
    plt.legend(loc='best')
    plt.legend(loc='best')
    plt.title("Cumulative explained variance vs Number of components")


cev_cv(np.arange(n_samples), cum_var_exp)